version: '3'
services:
  frontend:
    image: frontend-image:latest
    ports:
      - '5173:5173'
  backend:
    image: backend-image:latest
    ports:
      - '5000:5000'
    environment:
      - MONGO=mongodb+srv://vishnutha03:1234@cluster0.bzighwq.mongodb.net/
      - JWT=4de49e71da8814001d14d302b24519bb59ceabd68cc4e3dfdffac21bbd6dbfa49da2b4549d4fe37f87347c0bcc4c6634ca388fac10a21362e9a29e1049b9034c
      